#!/bin/sh

if [ -z "${STONESIGNAL_HOME}" ]
then
  echo "STONESIGNAL_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${STONESIGNAL_HOME}/lib" \
-m com.io7m.stonesignal.server/com.io7m.stonesignal.server.StMain \
"$@"
